------------
--DELETE DBS
------------
DROP DATABASE IF EXISTS A_STG
GO

DROP DATABASE IF EXISTS B_DW
GO

DROP DATABASE IF EXISTS C_DM
GO

------------
--CREATE DBS
------------
CREATE DATABASE A_STG COLLATE SQL_Latin1_General_CP1_CI_AS
GO

CREATE DATABASE B_DW COLLATE SQL_Latin1_General_CP1_CI_AS
GO

CREATE DATABASE C_DM COLLATE SQL_Latin1_General_CP1_CI_AS
GO

